spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dlg?serverTimezone=UTC
    username: root
    password: ipanel-dlg
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
#   空值属性不序列化
    default-property-inclusion: non_null

  thymeleaf:
    enabled: true
    prefix: classpath:/templates

server:
  port: 8080
  servlet:
    context-path: /PROMOD
