spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dlg?serverTimezone=UTC
    username: root
    password: ipanel-dlg
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
#   空值属性不序列化
    default-property-inclusion: non_null

  thymeleaf:
    enabled: true
    prefix: classpath:/templates
  redis:
    #password: 123456
    host: 192.168.56.1
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    # 项目名访问名配置
    context-path: /PROMOD
# 日志配置
logging:
  file: promod.log
  path: ./

